const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

// Load Env
const envPath = path.resolve(process.cwd(), '.env.local');
const envContent = fs.readFileSync(envPath, 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) env[match[1]] = match[2].trim();
});

const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

async function run() {
    console.log("Starting Schema Update...");

    // 1. Create 'attendance' table
    // Since we can't run raw SQL easily via JS client without an RPC or direct SQL access (which we might not have),
    // we will try to infer if we can create it via 'rpc' or just report what needs to be done.
    // However, if we are using Supabase JS Client, we usually can't create tables unless we have a specific RPC function for it.
    // WAIT: The user has `scripts/seed.js` which might delete/recreate tables if not careful.
    // Let's assume we might need to rely on the user to run SQL or use a workaround if we don't have DDL access.
    // But often `rpc` is available for 'exec_sql' or similar if set up.

    // Check if table exists by selecting from it
    const { error: checkError } = await supabase.from('attendance').select('id').limit(1);

    if (checkError && checkError.code === '42P01') { // undefined_table
        console.log("Table 'attendance' does not exist. Please create it with the following SQL in Supabase Dashboard:");
        console.log(`
CREATE TABLE public.attendance (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    member_id bigint references public.members(id),
    meeting_id bigint references public.agendas(id), -- This assumes Folder ID is an Agenda ID
    type text check (type in ('direct', 'proxy', 'written')),
    proxy_name text
);
        `);
        // If we can't execute SQL, we must stop and ask user or try to see if we have `rpc`.
    } else {
        console.log("Table 'attendance' seems to exist.");
    }

    // 2. Check 'agendas' columns
    const { data: agendaData, error: agendaError } = await supabase.from('agendas').select('votes_yes').limit(1);
    if (agendaError || !agendaData) {
        console.log("Column 'votes_yes' might be missing in 'agendas'. SQL to add:");
        console.log(`
ALTER TABLE public.agendas 
ADD COLUMN votes_yes integer default 0,
ADD COLUMN votes_no integer default 0,
ADD COLUMN votes_abstain integer default 0;
        `);
    } else {
        console.log("'agendas' table has vote columns.");
    }
}

run();
